apiVersion: batch/v1
kind: Job
metadata:
  name: whalesay
spec:
  backoffLimit: 6
  completions: 10
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: docker/whalesay
        name: whalesay
        command: ["sh","-c","cowsay I am going to ace CKAD!"]
        resources: {}
      restartPolicy: Never