apiVersion: v1
kind: Service
metadata:
  labels:
    app: drupal
  name: drupal-service
spec:
  ports:
  - port: 80
    protocol: TCP
    targetPort: 80
    nodePort: 30095
  selector:
    app: drupal
  type: NodePort
