---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: vote
  labels:
    app: db-deployment
  name: db-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: db-deployment
  template:
    metadata:
      labels:
        app: db-deployment
    spec:
      containers:
      - image: postgres:9.4
        name: db
        env:
          - name: POSTGRES_PASSWORD
            value: password
        volumeMounts:
          - name: db-data
            mountPath: /var/lib/postgresql/data
      volumes:
      - name: db-data
        emptyDir: {}
