---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: db-deployment
  name: db
  namespace: vote
spec:
  type: ClusterIP
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: db-deployment
