---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote-deployment
  name: vote-service
  namespace: vote
spec:
  type: NodePort
  ports:
  - port: 5000
    protocol: TCP
    targetPort: 80
    nodePort: 31000
  selector:
    app: vote-deployment
